medida = 
CALCULATE(
    COUNTROWS(
        BasedeDados
    ),
    FILTER(
        ALLSELECTED(
               BasedeDados[Campo]
        ),
        BasedeDados[Campo] <= MAX ( BasedeDados[Campo] )
    )
)